const CHANGE_RATING = 'CHANGE_RATING';

const ADD_ITEM = 'ADD_ITEM';

const REMOVE_ITEM = 'REMOVE_ITEM';

const ADD_REVIEW = 'ADD_REVIEW';

const LOAD_ALL_RESTAURANTS = 'LOAD_ALL_RESTAURANTS';

const START = '_START';

const SUCCESS = '_SUCCESS';

const ERROR = '_ERROR';

const LOAD_ALL_REVIEWS = 'LOAD_ALL_REVIEWS';

const LOAD_RESTAURANT_MENU = 'LOAD_RESTAURANT_MENU';

const LOAD_ALL_USERS = 'LOAD_ALL_USERS';

export {
    CHANGE_RATING,
    REMOVE_ITEM,
    ADD_ITEM,
    ADD_REVIEW,
    LOAD_ALL_RESTAURANTS,
    START,
    SUCCESS,
    ERROR,
    LOAD_ALL_REVIEWS,
    LOAD_RESTAURANT_MENU,
    LOAD_ALL_USERS,
};
