const CHANGE_RATING = 'CHANGE_RATING';

const ADD_ITEM = 'ADD_ITEM';

const REMOVE_ITEM = 'REMOVE_ITEM';

const ADD_REVIEW = 'ADD_REVIEW';

export { CHANGE_RATING, REMOVE_ITEM, ADD_ITEM, ADD_REVIEW };
